services:
  lucene:
    build:
      context: ./lucene
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    # ports:
    #   - "8001:8001"
    networks:
      - fainder-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - LUCENE_HOST=lucene
      - LUCENE_PORT=8001
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    networks:
      - fainder-network

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    environment:
      - NUXT_API_BASE=http://localhost:8000
    ports:
      - "3000:3000"
    networks:
      - fainder-network

networks:
  fainder-network:
    driver: bridge
