services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: backend
          target: /app
        - action: rebuild
          path: backend/pyproject.toml
    # user: ${UID:-1000}:${GID:-1000}
    environment:
      - FASTAPI_MODE=${FASTAPI_MODE:-run}
      - DATA_DIR=/app/data
      - COLLECTION_NAME=${COLLECTION_NAME:?COLLECTION_NAME is missing}
      - METADATA_FILE=${METADATA_FILE:-metadata.json}
      - HF_HUB_CACHE=/app/data/${COLLECTION_NAME}/${EMBEDDING_DIR:-embeddings}/model_cache
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    networks:
      - fainder-network

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: ui
          target: /app
        - action: rebuild
          path: ui/package.json
    # user: ${UID:-1000}:${GID:-1000}
    tmpfs: /tmp
    environment:
      - NUXT_MODE=${NUXT_MODE:-preview}
      - NUXT_API_BASE=http://localhost:8000
    ports:
      - "3000:3000"
    networks:
      - fainder-network

networks:
  fainder-network:
    driver: bridge
