name: Backend Tests

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/backend_tests.yml"
      - "backend/**"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/backend_tests.yml"
      - "backend/**"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.11"
          - "3.12"
          - "3.13"

    name: Python ${{ matrix.python }}

    env:
      DATA_DIR: ${{ github.workspace }}/backend/tests/assets
      COLLECTION_NAME: toy_collection
      LOG_LEVEL: DEBUG

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          working-directory: backend
          enable-cache: true
      - name: Install Python dependencies
        working-directory: backend
        run: uv sync --locked --dev
      - name: Run tests
        working-directory: backend
        run: uv run pytest tests --junitxml=tests/pytest.xml --cov=backend --cov-report=term-missing:skip-covered
